// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


function createEmail(str) {
  var re = new RegExp("\\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\\b");
  var match = re.test(str);
  if (match) {
    return /* Some */[/* Email */[str]];
  } else {
    return /* None */0;
  }
}

function createName(str) {
  if (str.length <= 50) {
    return /* Some */[str];
  } else {
    return /* None */0;
  }
}

exports.createEmail = createEmail;
exports.createName = createName;
/* No side effect */
