// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function createEmail(str) {
  var re = new RegExp("\\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\\b");
  var match = re.test(str);
  if (match) {
    return /* Some */[/* Email */[str]];
  } else {
    return /* None */0;
  }
}

function createZip(zip, country) {
  switch (country) {
    case 0 : 
        if (zip.length !== 5) {
          return /* None */0;
        } else {
          var exit = 0;
          var zip$1;
          try {
            zip$1 = Caml_format.caml_int_of_string(zip);
            exit = 1;
          }
          catch (exn){
            return /* None */0;
          }
          if (exit === 1) {
            return /* Some */[/* ZipDe */Block.__(0, [zip$1])];
          }
          
        }
        break;
    case 1 : 
        if (zip.length !== 4) {
          return /* None */0;
        } else {
          var exit$1 = 0;
          var zip$2;
          try {
            zip$2 = Caml_format.caml_int_of_string(zip);
            exit$1 = 1;
          }
          catch (exn$1){
            return /* None */0;
          }
          if (exit$1 === 1) {
            return /* Some */[/* ZipAt */Block.__(1, [zip$2])];
          }
          
        }
        break;
    case 2 : 
        var re = new RegExp("\\d{2}-\\d{3}$");
        var param = re.test(zip);
        if (param) {
          return /* Some */[/* ZipPl */Block.__(2, [zip])];
        } else {
          return /* None */0;
        }
    
  }
}

function createName(str) {
  if (str.length <= 50) {
    return /* Some */[str];
  } else {
    return /* None */0;
  }
}

function verificationService(email) {
  if (email === "voldemort@gmail.com") {
    return /* None */0;
  } else {
    return /* Some */[email];
  }
}

exports.createEmail = createEmail;
exports.createZip = createZip;
exports.createName = createName;
exports.verificationService = verificationService;
/* No side effect */
